version: '3.9'
services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.2
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME=local
      - MONGODB_DATABASE=parse
      - MONGODB_PASSWORD=local
  parse:
    image: docker.io/bitnami/parse:4
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami/parse'
    depends_on:
      - mongodb
    environment:
      - PARSE_HOST=127.0.0.1
      - PARSE_DATABASE_HOST=mongodb
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=local
      - PARSE_DATABASE_NAME=parse
      - PARSE_DATABASE_PASSWORD=local
  parse-dashboard:
    image: docker.io/bitnami/parse-dashboard:3
    ports:
      - '4040:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
    environment:
      - PARSE_HOST=192.168.178.59
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
