name: Deploy Angular

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --shamefully-hoist

      - name: Set deploy Path and API URL
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOY_PATH=${{ secrets.PROD_DEPLOY_PATH }}" >> $GITHUB_ENV
            echo "API_URL=${{ secrets.PROD_API_URL }}" >> $GITHUB_ENV
          else
            echo "DEPLOY_PATH=${{ secrets.DEV_DEPLOY_PATH }}" >> $GITHUB_ENV
            echo "API_URL=${{ secrets.DEV_API_URL }}" >> $GITHUB_ENV
          fi

      - name: Replace API URL in environment
        run: |
          sed -i "s|production: .*|production: true,|g" src/environments/environment.ts
          sed -i "s|url: .*|url: '${{ env.API_URL }}'|g" src/environments/environment.ts
          sed -i "s|production: .*|production: true,|g" src/environments/environment.prod.ts
          sed -i "s|url: .*|url: '${{ env.API_URL }}'|g" src/environments/environment.prod.ts

      - name: Build Angular app
        run: pnpm run build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

      - name: Clean server directory
        run: |
          ssh ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }} << 'EOF'
            if [ -d "${{ env.DEPLOY_PATH }}/frontend" ]; then
              echo "Cleaning existing deploy path..."
              rm -rf ${{ env.DEPLOY_PATH }}/frontend/*
            else
              echo "Creating directory..."
              mkdir -p ${{ env.DEPLOY_PATH }}/frontend
            fi
          EOF

      - name: Prepare upload
        run: |
          mkdir -p frontend
          cp -r dist/conserve/browser/* frontend/

      - name: Upload files
        run: |
          scp -r frontend/* \
            ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }}:${{ env.DEPLOY_PATH }}/frontend/

      - name: Reload service
        run: |
          ssh ${{ secrets.HOST_USER }}@${{ secrets.HOST_IP }} \
            "sudo systemctl reload ${{ secrets.SERVICE_NAME }}"
